### PR TITLE
MacOS packaging based on homebrew

### PR DESCRIPTION
**Pull request by lologor**
- For MacOS 13.3.1 / Clang 14.2
- Add homebrew based installation and build scripts (made for exiv2 0.27.6!)
- Some fixes related to macos / GTK on macos
- Supress some SSE warnings

### CODE REVIEW

**Comment by MStraeten** [comment]
don’t forget to complete the credits in BUILD_hb.txt ;)

**Comment by lologor** [comment]
> don’t forget to complete the credits in BUILD_hb.txt ;)

Will do. Thanks.

**Comment by aurelienpierre** [comment]
Manually rebased and pushed. Thanks !

**Comment by AlynxZhou** [comment]
I am getting `command \`sort\` failed with exit code 1` while running `1_install_hb_dependencies.sh`, don't know why `sort` returns 1, but I think whether sort succeed or not should not effect the process?

**Comment by AlynxZhou** [comment]
After removing sort, the error becomes following:

```
Error: command `( brew list --formula --quiet --versions ${standalone}; brew list --formula --quiet --versions ${deps} | sed -e 's/$/ (autoinstalled)/' )` failed with exit code 1
```

**Comment by AlynxZhou** [comment]
```
if [[ " ${hbInstalled[*]} " == *"${hbDependency}"* ]];
```

`luajit` matches `*lua*`, we should change the way of checking installed deps...

**Pull request closed without merging**
