### PR TITLE
Remove/Escape non-ASCII chars from source code and update translations

### PR DESCRIPTION
**Pull request by LucaZulberti**
I hope this modification is welcome. I think having non-ASCII chars in the source code can lead to unexpected behaviour in translation process (actually some sentences where not recognized in italian one with three dots (...), like `Export...`.
Furthermore, even for source code editors, having mixed ASCII and non-ASCII spaces can be annoying for Search&Replace tasks.
PO files can stay UTF-8 to make translator life easy with their non-ASCII chars.

This PR includes:
- [x] Remove/Escape non-ASCII chars from source code
- [x] Update `po/ansel.pot` using `cd po/ && intltool-update -p -g ansel`
- [x] Remove old translations using
```
for f in *.po ; do
  msgattrib --translated --no-fuzzy --no-obsolete -o $f $f
done
```
- [x] Improve italian translation `po/it.po
- [x] Update and check if other translations have been broken, using `cd po/ && intltool-update -g ansel -r`

Broken translations
===

I run  `cd po/ && intltool-update -g ansel -r` at master branch (807bd555bce901c2984386159f00f251a5b1760a) and at my PR.

Differences:
```diff
-af: 3115 translated messages, 772 fuzzy translations, 413 untranslated messages.
+af: 3099 translated messages, 789 fuzzy translations, 411 untranslated messages.
 
-ca: 1988 translated messages, 1313 fuzzy translations, 999 untranslated messages.
+ca: 1988 translated messages, 1314 fuzzy translations, 997 untranslated messages.
 
-cs: 3869 translated messages, 288 fuzzy translations, 143 untranslated messages.
+cs: 3847 translated messages, 310 fuzzy translations, 142 untranslated messages.
 
-da: 1984 translated messages, 1307 fuzzy translations, 1009 untranslated messages.
+da: 1984 translated messages, 1308 fuzzy translations, 1007 untranslated messages.
 
-de: 3834 translated messages, 335 fuzzy translations, 131 untranslated messages.
+de: 3812 translated messages, 358 fuzzy translations, 129 untranslated messages.
 
-el: 1254 translated messages, 1516 fuzzy translations, 1530 untranslated messages.
+el: 1254 translated messages, 1517 fuzzy translations, 1528 untranslated messages.
 
-eo: 3871 translated messages, 290 fuzzy translations, 139 untranslated messages.
+eo: 3849 translated messages, 312 fuzzy translations, 138 untranslated messages.
 
-es: 4109 translated messages, 134 fuzzy translations, 57 untranslated messages.
+es: 4081 translated messages, 162 fuzzy translations, 56 untranslated messages.
 
-fi: 3833 translated messages, 330 fuzzy translations, 137 untranslated messages.
+fi: 3811 translated messages, 353 fuzzy translations, 135 untranslated messages.
 
-fr: 4242 translated messages, 40 fuzzy translations, 18 untranslated messages.
+fr: 4203 translated messages, 78 fuzzy translations, 18 untranslated messages.
 
-gl: 231 translated messages, 1662 fuzzy translations, 2407 untranslated messages.
+gl: 231 translated messages, 1662 fuzzy translations, 2406 untranslated messages.
 
-he: 3831 translated messages, 332 fuzzy translations, 137 untranslated messages.
+he: 3809 translated messages, 355 fuzzy translations, 135 untranslated messages.
 
-hu: 3910 translated messages, 253 fuzzy translations, 137 untranslated messages.
+hu: 3888 translated messages, 276 fuzzy translations, 135 untranslated messages.
 
-it: 4242 translated messages, 39 fuzzy translations, 19 untranslated messages.
+it: 4262 translated messages, 24 fuzzy translations, 13 untranslated messages.
 
-ja: 3833 translated messages, 334 fuzzy translations, 133 untranslated messages.
+ja: 3811 translated messages, 356 fuzzy translations, 132 untranslated messages.
 
-nb: 1982 translated messages, 1299 fuzzy translations, 1019 untranslated messages.
+nb: 1982 translated messages, 1300 fuzzy translations, 1017 untranslated messages.
 
-nl: 3834 translated messages, 335 fuzzy translations, 131 untranslated messages.
+nl: 3812 translated messages, 358 fuzzy translations, 129 untranslated messages.
 
-pl: 3833 translated messages, 336 fuzzy translations, 131 untranslated messages.
+pl: 3811 translated messages, 359 fuzzy translations, 129 untranslated messages.
 
-pt_BR: 3833 translated messages, 326 fuzzy translations, 141 untranslated messages.
+pt_BR: 3811 translated messages, 348 fuzzy translations, 140 untranslated messages.
 
-pt_PT: 994 translated messages, 1598 fuzzy translations, 1708 untranslated messages.
+pt_PT: 994 translated messages, 1598 fuzzy translations, 1707 untranslated messages.
 
-ro: 440 translated messages, 1666 fuzzy translations, 2194 untranslated messages.
+ro: 440 translated messages, 1666 fuzzy translations, 2193 untranslated messages.
 
-ru: 3833 translated messages, 336 fuzzy translations, 131 untranslated messages.
+ru: 3811 translated messages, 359 fuzzy translations, 129 untranslated messages.
 
-sk: 2721 translated messages, 997 fuzzy translations, 582 untranslated messages.
+sk: 2706 translated messages, 1013 fuzzy translations, 580 untranslated messages.
 
-sl: 3833 translated messages, 330 fuzzy translations, 137 untranslated messages.
+sl: 3811 translated messages, 353 fuzzy translations, 135 untranslated messages.
 
-sq: 3733 translated messages, 400 fuzzy translations, 167 untranslated messages.
+sq: 3711 translated messages, 422 fuzzy translations, 166 untranslated messages.
 
-sr: 2837 translated messages, 962 fuzzy translations, 501 untranslated messages.
+sr: 2822 translated messages, 978 fuzzy translations, 499 untranslated messages.
 
-sr@latin: 2837 translated messages, 962 fuzzy translations, 501 untranslated messages.
+sr@latin: 2822 translated messages, 978 fuzzy translations, 499 untranslated messages.
 
-sv: 2246 translated messages, 1317 fuzzy translations, 737 untranslated messages.
+sv: 2233 translated messages, 1332 fuzzy translations, 734 untranslated messages.
 
-th: 268 translated messages, 1055 fuzzy translations, 2977 untranslated messages.
+th: 268 translated messages, 1057 fuzzy translations, 2974 untranslated messages.
 
-tr: 3833 translated messages, 326 fuzzy translations, 141 untranslated messages.
+tr: 3811 translated messages, 348 fuzzy translations, 140 untranslated messages.
 
-uk: 3833 translated messages, 330 fuzzy translations, 137 untranslated messages.
+uk: 3811 translated messages, 353 fuzzy translations, 135 untranslated messages.
 
-zh_CN: 4298 translated messages, 2 untranslated messages.
+zh_CN: 4265 translated messages, 32 fuzzy translations, 2 untranslated messages.
 
-zh_TW: 3826 translated messages, 332 fuzzy translations, 142 untranslated messages.
+zh_TW: 3804 translated messages, 354 fuzzy translations, 141 untranslated messages.
```

### CODE REVIEW

**Comment by aurelienpierre** [comment]
Nice, thanks

**Comment by LucaZulberti** [comment]
Hi @aurelienpierre, I updated the PR and put the before/after differences using `intltool-update -g ansel -r`.
If that is the correct way to test the validity of the translations, my PR downgraded to fuzzy some entries in all translations.
I fixed the Italian one, but it takes a little effort from other translators to fix them.

Is that acceptable to merge?

In the meantime, I continue to improve some entries in the Italian one.

**Comment by aurelienpierre** [comment]
Conflicting PR coming at around the same time. I will manually fix conflicts in the next days if you don't.

**Comment by LucaZulberti** [comment]
I will do it tomorrow 👍🏻

**Comment by aurelienpierre** [comment]
Manually rebased with 62a38008b42d42996dfcfb8d79541d50ea863786 -> 2aedaf869ac9132a4c54eb6b07a13481e01bdc50. Please have a look.

**Comment by LucaZulberti** [comment]
Awesome! Thank you!
Anyway, I think the uodate script added with cc40d8b93ec7e55453c325f77abff3ee5eed628b should not use `--no-fuzzy` because when sources changes, the intltool update could tag some valid entries fuzzy just to warn the user that something could be broken. Obsolete entries can be discarded, but fuzzy one should always be checked by translators.
What do you think?

**Comment by aurelienpierre** [comment]
Yes, that makes sense, I'll change that.

**Pull request closed without merging**
